name: Deploy to Firebase on merge
"on":
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing Dependencies
        working-directory: ./functions
        run: yarn
      - name: Building App
        working-directory: ./functions
        run: yarn run build
      - name: Linting
        working-directory: ./functions
        run: yarn run lint
      - name: Running Tests
        working-directory: ./functions
        run: yarn run test
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Deploying to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_SECRET }}"
